# Generated by Django 3.1 on 2021-06-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('User', 'user'), ('Agent', 'Agent'), ('Admin', 'Admin'), ('Super_Admin', 'Super Admin'), ('Developer', 'Developer')], default='User', max_length=50),
        ),
    ]
