# Generated by Django 3.1 on 2021-06-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_environment', models.CharField(blank=True, max_length=350, verbose_name='Mpesa Environment')),
                ('mpesa_consumer_key', models.CharField(blank=True, max_length=350, verbose_name='Mpesa Consumer Key')),
                ('mpesa_consumer_secret', models.CharField(blank=True, max_length=350, verbose_name='Mpesa Consumer Secret')),
                ('mpesa_shortcode', models.CharField(blank=True, max_length=350, verbose_name='Mpesa Short Code')),
                ('mpesa_express_shortcode', models.CharField(blank=True, max_length=350, verbose_name='Mpesa Express Short Code')),
                ('mpesa_shortcode_type', models.CharField(blank=True, max_length=350, verbose_name='Mpesa Short Code Type')),
                ('mpesa_passkey', models.CharField(blank=True, max_length=350, verbose_name='Mpesa Passkey')),
                ('mpesa_initiator_username', models.CharField(blank=True, max_length=350, verbose_name='Mpesa Initiator Username')),
                ('mpesa_initiator_security_credential', models.CharField(blank=True, max_length=350, verbose_name='Mpesa Initiator Security Credential')),
            ],
            options={
                'db_table': 'System configuration',
            },
        ),
    ]
