# Generated by Django 3.1 on 2021-06-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualSchoolFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('fees', models.IntegerField(verbose_name='Fees')),
            ],
            options={
                'db_table': 'Annual school fees',
            },
        ),
        migrations.CreateModel(
            name='MaximumAmountAllowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(verbose_name='Amount')),
            ],
            options={
                'db_table': 'Maximum premium allowed',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
            ],
            options={
                'db_table': 'Policy type',
            },
        ),
        migrations.CreateModel(
            name='PremiumRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('rate', models.FloatField(verbose_name='Rate in %')),
            ],
            options={
                'db_table': 'Premium rate',
            },
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('school_level', models.CharField(max_length=50, verbose_name='school level')),
            ],
            options={
                'db_table': 'School levels',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('tax', models.FloatField(verbose_name='Tax in %')),
            ],
            options={
                'db_table': 'Tax rate',
            },
        ),
        migrations.CreateModel(
            name='PolicyFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField(verbose_name='Feature')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.policy', verbose_name='Policy Features')),
            ],
            options={
                'db_table': 'Policy Features',
            },
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.TextField(verbose_name='Benefit')),
                ('premium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.maximumamountallowed', verbose_name='Premium')),
            ],
            options={
                'db_table': 'Benefits(ie a premium can have multiple benefits )',
            },
        ),
    ]
