# Generated by Django 3.1 on 2021-05-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('subject', models.CharField(max_length=70, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('seen', models.BooleanField(default=False)),
                ('responded', models.BooleanField(default=False, verbose_name='Contacted')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('converted', models.CharField(choices=[('No', 'NO'), ('Yes', 'Yes'), ('NA', 'Not applicabe')], default='NO', max_length=50, verbose_name='Converted?')),
                ('served_by', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'Contact us',
            },
        ),
        migrations.CreateModel(
            name='QuoteLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('order_number', models.CharField(max_length=50, verbose_name='Order number')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('dob', models.DateField(verbose_name='Parents DoB')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone number')),
                ('annual_fees', models.IntegerField(verbose_name='Annual school fees')),
                ('premium', models.IntegerField(verbose_name='premium')),
                ('tax', models.IntegerField(default=0, verbose_name='Tax')),
                ('total', models.IntegerField(default=0, verbose_name='Total')),
                ('education_level', models.CharField(max_length=70, verbose_name='Child.s Education level')),
                ('school_years', models.IntegerField(verbose_name='No of school years')),
                ('sum_assured', models.IntegerField(blank=True, verbose_name='sum_assured')),
                ('contacted', models.BooleanField(default=False, verbose_name='Contacted')),
                ('converted', models.BooleanField(default=False, verbose_name='Converted')),
                ('served_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Quote Leads',
            },
        ),
    ]
