INSTALLED_APPS = [
    'baton',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',

    'ckeditor',
    'mathfilters',
    'hijack_admin',
    'hijack',
    'compat',
    'simplemathcaptcha',
    'crispy_forms',
    'django_daraja',
    'tabular_permissions',
    'sorl.thumbnail',
    'tinymce',
    'newsletter',
    # 'admin_reorder',
    'import_export',
    # testing remove on production
    'django_seed',
    'report_builder',
    'reversion',
    'django_user_agents',
    'logentry',
    'django_login_history',
    'treenode',
    'mlmtools',
    'floppyforms',



    'core',
    'configuration',
    'authentication.accounts',
    'website',
    'website.blog',
    'website.cms',
    'leads',
    'claims',
    'checkout',
    'payments.mpesa',
    'customer',
    'order',
    'agent',
    'communication',
    'baton.autodiscover',
]
