# Generated by Django 3.1 on 2021-06-15 09:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentAccount',
            new_name='AgentBankAccount',
        ),
    ]
