# Generated by Django 3.1 on 2021-05-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssection',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='clientsfeedbacks',
            name='content',
            field=models.TextField(verbose_name='What they say about elimusmart'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='mission',
            field=models.TextField(verbose_name='Our mission'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='primary_content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='mainabout',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='ouradvantage',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
    ]
