# Generated by Django 3.1 on 2021-05-31 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('mpesa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(default=0, max_length=50, verbose_name='Documents Number')),
                ('id_front', models.FileField(upload_to='user/docs/nationalID/', verbose_name='ID Front')),
                ('id_back', models.FileField(upload_to='user/docs/nationalID/', verbose_name='ID Back')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'db_table': 'ID Images',
            },
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('kyc_id', models.CharField(max_length=50, verbose_name='KYC Number')),
                ('names', models.CharField(max_length=50, verbose_name="Applicant's Names as per ID")),
                ('nationality', django_countries.fields.CountryField(max_length=2, verbose_name='Nationality')),
                ('id_national', models.IntegerField(verbose_name='National ID/Passport NO')),
                ('kra_pin', models.CharField(max_length=50, verbose_name='KRA PIN Number')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, verbose_name='Gender')),
                ('marital_status', models.CharField(choices=[('Divorced', 'Divorced'), ('Married', 'Married'), ('Single', 'Single')], max_length=50, verbose_name='Marital Status')),
                ('occupation', models.CharField(max_length=50, verbose_name='Occupation')),
                ('phone', models.IntegerField(verbose_name='Phone number')),
                ('dob', models.CharField(max_length=50, verbose_name='Date of Birth')),
                ('sum_assured', models.IntegerField(verbose_name='Sum Assured')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('postal_code', models.CharField(max_length=50, verbose_name='Postal Code')),
                ('name_of_school', models.CharField(max_length=50, verbose_name='Name of School')),
                ('school_county', models.CharField(choices=[('Baringo', 'Baringo'), ('Bomet', 'Bomet'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Elgeyo Marakwet', 'Elgeyo Marakwet'), ('Embu', 'Embu'), ('Garissa', 'Garissa'), ('Homabay', 'Homabay'), ('Isiolo', 'Isiolo'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Kericho', 'Kericho'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Kirinyaga', 'Kirinyaga'), ('Kisii', 'Kisii'), ('Kisumu', 'Kisumu'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Laikipia', 'Laikipia'), ('Lamu', 'Lamu'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Meru', 'Meru'), ('Migori', 'Migori'), ('Mombasa', 'Mombasa'), ("Murang'a", 'Murang`a'), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Nandi', 'Nandi'), ('Narok', 'Narok'), ('Nyamira', 'Nyamira'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Samburu', 'Samburu'), ('Siaya', 'Siaya'), ('Taita Taveta', 'Taita Taveta'), ('Tana River', 'Tana River'), ('Trans Nzoia', 'Trans Nzoia'), ('Tharaka Nithi', 'Tharaka Nithi'), ('Turkana', 'Turkana'), ('Uasin Gishu', 'Uasin Gishu'), ('Vihiga', 'Vihiga'), ('Wajir', 'Wajir'), ('West Pokot', 'West Pokot')], max_length=50, verbose_name='School County')),
                ('school_type', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], max_length=50, verbose_name='School Type')),
                ('school_level', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('University/College', 'University/College')], max_length=50, verbose_name='School Level')),
                ('nominee_names', models.CharField(max_length=50, verbose_name='Nominee Name')),
                ('nominee_relationship', models.CharField(max_length=50, verbose_name='Relationship with Parent')),
                ('nominee_dob', models.CharField(max_length=50, verbose_name='Date of Birth')),
                ('nominee_phone', models.IntegerField(verbose_name='Phone Number')),
                ('status', models.CharField(choices=[('Submit', 'Submit KYC'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submit', max_length=20, verbose_name='Status')),
                ('docs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.docs', verbose_name='Documents')),
            ],
            options={
                'db_table': 'KYC',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('order_number', models.CharField(max_length=50, verbose_name='Order Number')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('category', models.CharField(default='Term Life Insurance', max_length=70, verbose_name='Category')),
                ('package_name', models.CharField(default='Annual Premium', max_length=70, verbose_name='Package Category')),
                ('product_name', models.CharField(default='Elimu Smart', max_length=70)),
                ('tax', models.IntegerField(verbose_name='Tax')),
                ('premium', models.IntegerField(verbose_name='Premium')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('status', models.CharField(choices=[('Submit', 'Submit KYC'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Status')),
                ('features', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.policy', verbose_name='Policy Feature')),
                ('kyc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.kyc', verbose_name='KYC')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.quoteleads', verbose_name='Lead')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mpesa.successmpesapayments', verbose_name='Payments')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_names', models.CharField(max_length=50, verbose_name='Name')),
                ('beneficiary_allocation', models.IntegerField(verbose_name='Allocation in %')),
                ('beneficiary_dob', models.CharField(max_length=50, verbose_name='DoB')),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.kyc', verbose_name='KYC')),
            ],
            options={
                'db_table': 'Beneficiary',
            },
        ),
    ]
