# Generated by Django 3.1 on 2021-07-03 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='reject_reason',
            field=models.CharField(default='', max_length=70, verbose_name='Reason for Rejecting KYC'),
        ),
    ]
