# Generated by Django 3.1 on 2021-06-12 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_allocation',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Allocation in  %'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_dob',
            field=models.CharField(max_length=50, verbose_name='Date of Birth'),
        ),
    ]
