# Generated by Django 3.1 on 2021-06-14 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210612_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='id_or_birth_cert_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID/Birth Cert No'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='no',
            field=models.BooleanField(default=True, verbose_name='Not a US Citizen'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='public_office',
            field=models.BooleanField(default=False, verbose_name='Hold a public office?'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='relative_public_office',
            field=models.BooleanField(default=False, verbose_name='Relative holds a public office?'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='sign_four',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='sign_one',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='sign_three',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='sign_two',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='source_of_income',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Source of Premium'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='yes',
            field=models.BooleanField(default=False, verbose_name='A USA Citizen'),
        ),
    ]
