# Generated by Django 3.1 on 2021-05-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllMpesaTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_id', models.TextField(blank=True, verbose_name='merchant id')),
                ('checkout_request_id', models.TextField(blank=True, verbose_name='checkout request id')),
                ('Result_code', models.TextField(blank=True, verbose_name='Result code')),
                ('Result_description', models.TextField(blank=True, verbose_name='result description')),
            ],
            options={
                'verbose_name': 'All mpesa transaction',
                'verbose_name_plural': 'All Mpesa transactions',
            },
        ),
        migrations.CreateModel(
            name='MpesaCalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.TextField(default='safaricom')),
                ('caller', models.TextField(default='APP#1')),
                ('conversation_id', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Mpesa Call/dev',
                'verbose_name_plural': 'Mpesa Calls/dev',
            },
        ),
        migrations.CreateModel(
            name='SuccessMpesaPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SystemDate', models.DateTimeField(auto_now_add=True, verbose_name='System date')),
                ('merchant_id', models.TextField(blank=True, verbose_name='merchant id')),
                ('checkout_request_id', models.TextField(blank=True, verbose_name='checkout request id')),
                ('Result_code', models.TextField(blank=True, verbose_name='Result code')),
                ('Result_description', models.TextField(blank=True, verbose_name='result description')),
                ('Amount', models.TextField(blank=True)),
                ('Receipt', models.TextField(blank=True)),
                ('Balance', models.IntegerField(blank=True, default=0)),
                ('TransactionDate', models.TextField(blank=True, verbose_name='transaction date')),
                ('PhoneNumber', models.TextField(blank=True, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'Successful Mpesa transactions',
                'verbose_name_plural': 'Successful Mpesa transactions',
            },
        ),
    ]
